import React from 'react';
import { Inter } from "next/font/google";
import Image from "next/image";
/* == bootstrap == */
import {$,jQuery} from 'jquery';
import "bootstrap/dist/css/bootstrap.min.css";
/* == owl.carousel == */
import styles from "./css/plugins/owl.carousel.min.css";
import "./css/plugins/owl.theme.default.min.css";
/* == animate css == */
import "./css/plugins/animate.min.css";
/* == themify icons ==*/
import "./css/plugins/themify-icons.css";
/* == et-lineicons icons ==*/
import "./css/plugins/et-lineicons.css";
/* == magnific-popup gallery  == */
import "./css/plugins/magnific-popup.css";
/* == YouTubePopUp == */
import "./css/plugins/YouTubePopUp.css";
/* == for booking css == */
import "./css/plugins/select2.css";
import "./css/plugins/datepicker.css";
import "./globals.css";
// import ScriptTag from "./js/jquery-3.6.3.min.js";
// import "./js/popper.min.js";
// import "./js/bootstrap.min.js";
// import "./js/scrollIt.min.js";
// import "./js/jquery.waypoints.min.js";
// import "./js/owl.carousel.min.js";
// import "./js/jquery.stellar.min.js";
// import "./js/jquery.magnific-popup.js";
// import "./js/YouTubePopUp.js";
// import "./js/select2.js";
// import "./js/jquery.stellar.min.js";
// import "./js/datepicker.js";
// import "./js/custom.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  descriptTagion: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
        <title>Michael Corker - Artwork</title>
        <link rel="shortcut icon" href="img/favicon.png" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Barlow:wght@300;400;500;600;700&family=Oswald:wght@300;400;500;600;700&display=swap"
        />
      </head>
        <body className={inter.className}>{children}
          {/* <scriptTag type="text/javascript" src="./js/jquery-3.6.3.min.js"></scriptTag>
          <scriptTag type="text/javascript" src="./js/jquery-migrate-3.0.0.min.js"></scriptTag>
          <scriptTag type="text/javascript" src="./js/modernizr-2.6.2.min.js"></scriptTag>
          <scriptTag type="text/javascript" src="./js/popper.min.js"></scriptTag>
          <scriptTag type="text/javascript" src="./js/bootstrap.min.js"></scriptTag>
          <scriptTag type="text/javascript" src="./js/scrollIt.min.js"></scriptTag>
          <scriptTag type="text/javascript" src="./js/jquery.waypoints.min.js"></scriptTag>
          <scriptTag type="text/javascript" src="./js/owl.carousel.min.js"></scriptTag>
          <scriptTag type="text/javascript" src="./js/jquery.stellar.min.js"></scriptTag>
          <scriptTag type="text/javascript" src="./js/jquery.magnific-popup.js"></scriptTag>
          <scriptTag type="text/javascript" src="./js/YouTubePopUp.js"></scriptTag>
          <scriptTag type="text/javascript" src="./js/select2.js"></scriptTag>
          <scriptTag type="text/javascript" src="./js/datepicker.js"></scriptTag>
          <scriptTag type="text/javascript" src="./js/custom.js"></scriptTag> */}
        </body>
    </html>
  );
}
