import { Inter } from "next/font/google";
import Image from "next/image";
/* == bootstrap == */
import "./../css/plugins/bootstrap.min.css";
/* == owl.carousel == */
import "./../css/plugins/owl.carousel.min.css";
import "./../css/plugins/owl.theme.default.min.css";
/* == animate css == */
import "./../css/plugins/animate.min.css";
/* == themify icons ==*/
import "./../css/plugins/themify-icons.css";
/* == et-lineicons icons ==*/
import "./../css/plugins/et-lineicons.css";
/* == magnific-popup gallery  == */
import "./../css/plugins/magnific-popup.css";
/* == YouTubePopUp == */
import "./../css/plugins/YouTubePopUp.css";
/* == for booking css == */
import "./../css/plugins/select2.css";
import "./../css/plugins/datepicker.css";
import "./globals.css";
import styles from "./page.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  descriptTagion: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
        <title>Michael Corker - Artwork</title>
        <link rel="shortcut icon" href="img/favicon.png" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Barlow:wght@300;400;500;600;700&family=Oswald:wght@300;400;500;600;700&display=swap"
        />
        <link rel="stylesheet" href="css/plugins.css" />
        <link rel="stylesheet" href="css/style.css" />
      </head>
        <body className={inter.className}>{children}
          <script src="js/jquery-3.6.3.min.js"></script>
          <script src="js/jquery-migrate-3.0.0.min.js"></script>
          <script src="js/modernizr-2.6.2.min.js"></script>
          <script src="js/popper.min.js"></script>
          <script src="js/bootstrap.min.js"></script>
          <script src="js/scrollIt.min.js"></script>
          <script src="js/jquery.waypoints.min.js"></script>
          <script src="js/owl.carousel.min.js"></script>
          <script src="js/jquery.stellar.min.js"></script>
          <script src="js/jquery.magnific-popup.js"></script>
          <script src="js/YouTubePopUp.js"></script>
          <script src="js/select2.js"></script>
          <script src="js/datepicker.js"></script>
          <script src="js/custom.js"></script>
        </body>
    </html>
  );
}
